name: timeflow
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.7.2
  get_storage: ^2.1.1
  intl: ^0.19.0
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
