// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-fLleKP9AFMB_a4WCbiBlIH8bzA43wOc',
    appId: '1:603858523844:web:8870bafb03abbc4b8adb91',
    messagingSenderId: '603858523844',
    projectId: 'timeflow-f8697',
    authDomain: 'timeflow-f8697.firebaseapp.com',
    storageBucket: 'timeflow-f8697.firebasestorage.app',
    measurementId: 'G-PSW6GN8LL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfgP5wRgvLYJyNXvux1IGtcvz2IDqd9X8',
    appId: '1:603858523844:android:dfbbdcd020f0f1088adb91',
    messagingSenderId: '603858523844',
    projectId: 'timeflow-f8697',
    storageBucket: 'timeflow-f8697.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-fLleKP9AFMB_a4WCbiBlIH8bzA43wOc',
    appId: '1:603858523844:web:83f4c37176e574328adb91',
    messagingSenderId: '603858523844',
    projectId: 'timeflow-f8697',
    authDomain: 'timeflow-f8697.firebaseapp.com',
    storageBucket: 'timeflow-f8697.firebasestorage.app',
    measurementId: 'G-KCGHSLF8V8',
  );
}
